name: Build and Deploy NestJS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x' # Ensure this matches the Node.js version of your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Set environment variables from GitHub Secrets
      - name: Set environment variables
        run: |
          echo "AMADEUS_API_KEY=${{ secrets.AMADEUS_API_KEY }}" >> $GITHUB_ENV
          echo "AMADEUS_API_SECRET=${{ secrets.AMADEUS_API_SECRET }}" >> $GITHUB_ENV

      # Step 5: Build the project
      - name: Build the project
        run: npm run build
