name: Build and Deploy NestJS App

on:
  push:
    branches:
      - master  # Change branch to master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Update Node.js version to 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Upload dist/ directory as artifact
      - name: Upload dist directory
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist/
